version: "2.2"
services:
  iris:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 51773:51773
      - 52773:52773
    volumes:
      - ./:/irisdev/app